name: BossDoors
main: com.streep.bossdoors.Main
version: 1.0
api-version: 1.14.4
commands:
   bosskey:
      description: Bosskey command
      usage: /bosskey info
   bossdoor:
      description: Bossdoor command 
      usage: /bossdoor info